[package]
name = "thrust"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"

[workspace]
members = [
    "crates/advent_of_code",
    "crates/axum_crud",
    "crates/crud_api",
    "crates/md_badges",
]
exclude = [
    "projects/rlog",
]
